# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 5f6f8564a4c71e83ecc3671a5d65b6b82d04d47c4dfc49d14ab7d4fa58554a755306ac8eec47b092aa7bb3cc04e19e154d65e23869ecac16fb044f5f211ee93a

test:
  secret_key_base: ee833be9a08e5e888ba453e430358fd170ab10f74b2b00b90197d57a71052fa19176d0f8b4d1998faf134ae9b01ad22c286c61e1d091927d4b54374a5f133731

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
